# Generated by Django 4.2 on 2023-04-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_detailed',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Description detailed'),
        ),
    ]
