# Generated by Django 4.2 on 2023-05-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_description_detailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_detailed_additional',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Additional description detailed'),
        ),
    ]
